chore: add circleci config to auto publish docker images

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,30 +1,68 @@
 version: 2
-
 jobs:
-  build:
+  test:
     docker:
-      - image: circleci/node:7.10
-
+      - image: circleci/node:8.9
     steps:
       - checkout
+
+      # Restore cache from last test run
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "package.json" }}
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
+
+      - run:
+          name: "Install dependencies"
+          command: yarn
+
+      # Save cache for a future test run
+      - save_cache:
+          paths:
+            - node_modules
+          key: v1-dependencies-{{ checksum "package.json" }}
+
+      - run:
+          name: "Run tests"
+          command: yarn test-ci
+
+  build:
+    docker:
+      - image: circleci/node:8.9
+    steps:
+      - checkout
+
       - run:
           name: "Add npm token to npmrc"
           command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
       - run:
-          name: "Install js dependencies"
-          command: yarn
-      - run:
-          name: "Run tests"
-          command: yarn test-ci
-      - run:
           name: "Publish npm package"
           command: |
-            if [ "$CIRCLE_BRANCH" == "master" ]; then
-              echo "Trying to publish package, if it fails then this verison has already been published."
-              set +e
-              npm publish .
-              set -e
-            else
-              echo "Packages are only published to npm on branch 'master'."
-            fi
-            exit 0
+            echo "Trying to publish package, if it fails then this verison has already been published."
+            set +e
+            npm publish .
+            set -e
+
+      - setup_remote_docker
+      - run:
+          name: Build container image
+          command: 'docker build -t backstroke/worker:latest .'
+      - run:
+          name: Login to Docker Hub
+          command: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
+      - run:
+          name: Push container image
+          command: 'docker push backstroke/worker:latest'
+
+workflows:
+  version: 2
+  build_and_test:
+    jobs:
+      - test
+      - build:
+          requires:
+            - test
+          filters:
+            branches:
+              only: master
